<?php
return array (
    'rk_assets_url'=>'http://221.232.160.243/bolanadmin/front/assets/',
    'rk_url'=>'http://221.232.160.243/bolanadmin/home/index.php?a=gethis',
    'rk_content_url'=>'http://221.232.160.243/bolanadmin/home/index.php?cid=',
    'rk_js_url'=>'http://221.232.160.243/bolanadmin/home/index.php?a=ccc',
    'rk_dir'=>'file:////home/rk/',
    'rk_copyright'=>"",
    'rk_path' => '/home/wwwroot/default/bolanadmin/admin/rk/',
    'rk_conf'=>array(
        /////////////////////////决策内参//////////////////////////////////////////
        array("classId"=>"C215","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"中国首席财经"),//0中国首席财经
        array("classId"=>"C220","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"首席证券内参"),//1首席证券内参
        array("classId"=>"C222","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"金融机构内参"),//2金融机构内参
        array("classId"=>"C232","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"高层决策内参"),//3高层决策内参
        array("classId"=>"C227","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"首席银行内参"),//4首席银行内参
        //////////////////////////股市参考/////////////////////////////////////////
        array("classId"=>"C221","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"证券特情资讯"),//5证券特情资讯
        array("classId"=>"C224","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"趋势策略资讯"),//6趋势策略资讯
        array("classId"=>"C225","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"个股精研资讯"),//7个股精研资讯
        array("classId"=>"C226","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"板块联动资讯"),//8板块联动资讯
        /////////////////////////
        array("classId"=>"C4301","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"打新专刊"),//9打新专刊
        array("classId"=>"C5490","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"两融投资参考"),//10两融投资参考
        array("classId"=>"C5491","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"港股投资参考"),//11港股投资参考
        array("classId"=>"C229","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"香港股市参考"),//12香港股市参考
        array("classId"=>"C223","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"每日A股参考"),//13每日A股参考
        //////////////////////////国际资讯//////////////////////////////////////////
        array("classId"=>"C219","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"环球财经资讯"),//14环球财经资讯
        array("classId"=>"C911","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"每日国际参考"),//15每日国际参考
        ///////////////////////////精华周刊////////////////////////////////////////////////
        array("classId"=>"C230","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"首席证券周刊"),//16首席证券周刊
        array("classId"=>"C231","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"首席财经周刊"),//17首席财经周刊
        array("classId"=>"C233","lefttitle"=>"","righttitle"=>"","template"=>"template0.html","title"=>"点金周刊"),//18点金周刊
         ///////////////////////////外包////////////////////////////////////////////////
        array("classId"=>"C5500","lefttitle"=>"","righttitle"=>"","template"=>"template19.html","title"=>"与庄共舞"),//19与庄共舞
        array("classId"=>"C5564","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"国策精研"),//20国策精研
        array("classId"=>"C5566","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"宏观研究（资产配置）"),//21宏观研究（资产配置）
        array("classId"=>"C5568","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"行业主题研究"),//22行业主题研究
        array("classId"=>"C5570","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"专题研究报告"),//23专题研究报告
        array("classId"=>"C5572","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"大事速评"),//24大事速评
        array("classId"=>"C5574","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"钻“研”论市"),//25钻“研”论市
        array("classId"=>"C5576","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"VIP服务计划书"),//26VIP服务计划书
        array("classId"=>"C5578","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"操盘计划"),//27操盘计划
        array("classId"=>"C5580","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"主题投资"),//28主题投资
        array("classId"=>"C5582","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"策马扬鞭（周策略）"),//29策马扬鞭（周策略）
        array("classId"=>"C5584","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"策马扬鞭（月策略）"),//30策马扬鞭（月策略）
        array("classId"=>"C5586","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"盘前早知道"),//31盘前早知道
        array("classId"=>"C5588","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"晨报速递"),//32晨报速递
        array("classId"=>"C5590","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"涨停板预测"),//33涨停板预测
        array("classId"=>"C5592","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"收盘鸣金"),//34收盘鸣金
        array("classId"=>"C5594","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"投资日历"),//35投资日历
        array("classId"=>"C5596","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"异动分析"),//36异动分析
        array("classId"=>"C5598","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"操盘短信"),//37操盘短信
        array("classId"=>"C5600","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"分级每日报"),//38分级每日报
        array("classId"=>"C5602","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"分级晚汇报"),//39分级晚汇报
        array("classId"=>"C5604","lefttitle"=>"","righttitle"=>"","template"=>"template44.html","title"=>"券商客户服务内刊"),//40券商客户服务内刊

    ),
);

?>