<?php
return array (
  55 => 
  array (
    'typeid' => '55',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '热点聚焦',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  56 => 
  array (
    'typeid' => '56',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '博览视点',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  59 => 
  array (
    'typeid' => '59',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '焦点透视',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  60 => 
  array (
    'typeid' => '60',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '新闻观察',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  61 => 
  array (
    'typeid' => '61',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '决策参考',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  62 => 
  array (
    'typeid' => '62',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '投资参考',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  63 => 
  array (
    'typeid' => '63',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '新视野',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  64 => 
  array (
    'typeid' => '64',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '金融观察',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  65 => 
  array (
    'typeid' => '65',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '债券市场',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  66 => 
  array (
    'typeid' => '66',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '银行业',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  67 => 
  array (
    'typeid' => '67',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '信托业',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  68 => 
  array (
    'typeid' => '68',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '商学院',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  69 => 
  array (
    'typeid' => '69',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '温故知新',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  70 => 
  array (
    'typeid' => '70',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '政经观察',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
);
?>